spring.application.name=ejemploapi
# Habilitar consola web de H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configuración de conexión H2 en memoria
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Crear las tablas automáticamente si usás @Entity
spring.jpa.hibernate.ddl-auto=update
# Configuración de JPA
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# Mostrar las consultas SQL en consola (opcional para debug)
spring.jpa.show-sql=true

spring.sql.init.mode=always
